language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install -qq libxml2

install:
  - pip install -U tox-travis

script: tox

branches:
  only:
    - master

notifications:
  email:
    - gback@mitre.org
    - stix-commits-list@lists.mitre.org
